import logging
import sys
import os
from datetime import timezone, datetime
from typing import List

from models import FreeFoodEvent
from services.mq import Consumer
from services.config import REDIS_URL, MQ_STREAM
from services.notification.notifier import (
    SMTPNotifier,
    NotificationManager,
    render_template,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)

logger = logging.getLogger(__name__)


def _get_recipients() -> List[str]:
    raw = os.environ.get("NOTIFICATION_RECIPIENTS", "")
    if not raw:
        return []
    return [r.strip() for r in raw.split(",") if r.strip()]


def _get_smtp_config() -> dict:
    """Get SMTP configuration from environment variables."""
    return {
        "smtp_server": os.environ.get("SMTP_SERVER", "smtp.gmail.com"),
        "smtp_port": int(os.environ.get("SMTP_PORT", "465")),
        "smtp_user": os.environ.get("SMTP_USER", ""),
        "smtp_password": os.environ.get("SMTP_PASSWORD", ""),
        "use_ssl": os.environ.get("USE_SSL", "true").lower() == "true",
        "use_starttls": os.environ.get("USE_STARTTLS", "false").lower() == "true",
        "dry_run": os.environ.get("DRY_RUN", "false").lower() == "true",
    }


class NotificationProcessor:
    def __init__(self, manager: NotificationManager):
        self.manager = manager
        self.events_processed = 0
        self.events_failed = 0
        self.start_time = datetime.now(timezone.utc)

    def process_event(self, event: FreeFoodEvent) -> None:
        try:
            logger.info(
                f"Processing event {event.event_id} — {event.title} @ {event.location}"
            )

            subject_tpl = "🍕 Free Food Alert: {{ title }} at {{ location or 'TBD' }}"
            body_tpl = """
<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
    <div style="background-color: #4CAF50; color: white; padding: 20px; text-align: center;">
        <h2>🍕 Free Food Event!</h2>
    </div>
    <div style="padding: 20px; background-color: #f9f9f9;">
        <h3 style="color: #333;">{{ title }}</h3>
        
        <div style="background-color: white; padding: 15px; border-radius: 5px; margin: 10px 0;">
            <p style="margin: 5px 0;"><strong>📍 Location:</strong> {{ location or 'TBD' }}</p>
            <p style="margin: 5px 0;"><strong>🕐 Time:</strong> {{ start_time or 'TBD' }}</p>
            <p style="margin: 5px 0;"><strong>🎯 Confidence:</strong> {{ (llm_confidence * 100)|round }}%</p>
        </div>
        
        {% if description %}
        <div style="background-color: white; padding: 15px; border-radius: 5px; margin: 10px 0;">
            <p><strong>Details:</strong></p>
            <p style="color: #666;">{{ description }}</p>
        </div>
        {% endif %}
        
        <div style="margin-top: 20px; padding: 10px; background-color: #e8f5e9; border-left: 4px solid #4CAF50;">
            <p style="margin: 5px 0; font-size: 12px; color: #666;">
                This alert was generated by the Free Food Detection System
            </p>
        </div>
    </div>
</body>
</html>
            """

            context = {
                "title": event.title,
                "location": event.location,
                "start_time": event.start_time.strftime("%A, %B %d at %I:%M %p")
                if event.start_time
                else None,
                "description": event.description,
                "llm_confidence": event.llm_confidence or 0.0,
            }

            subject = render_template(subject_tpl, context)
            body = render_template(body_tpl, context)

            recipients = _get_recipients()
            if not recipients:
                logger.warning(
                    "No recipients configured (NOTIFICATION_RECIPIENTS). Skipping send."
                )
                return

            for r in recipients:
                ok_map = self.manager.notify_all(
                    r, subject, body, attachments=None, meta=event.model_dump()
                )
                logger.info(f"Send result for {r}: {ok_map}")

            self.events_processed += 1

        except Exception as e:
            self.events_failed += 1
            logger.error(
                f"Failed to process/notify for event {event.event_id}: {e}",
                exc_info=True,
            )
            raise


def main():
    logger.info("Starting Notification Service")
    logger.info(f"Redis URL: {REDIS_URL}")
    logger.info(f"Stream: {MQ_STREAM}")

    # Get SMTP configuration from environment
    smtp_config = _get_smtp_config()
    
    logger.info(f"SMTP Server: {smtp_config['smtp_server']}")
    logger.info(f"SMTP Port: {smtp_config['smtp_port']}")
    logger.info(f"SMTP User: {smtp_config['smtp_user']}")
    logger.info(f"Use SSL: {smtp_config['use_ssl']}")
    logger.info(f"Dry Run: {smtp_config['dry_run']}")
    
    # Check if SMTP credentials are configured
    if not smtp_config['smtp_user'] or not smtp_config['smtp_password']:
        logger.warning("⚠️  SMTP_USER or SMTP_PASSWORD not set in environment!")
        logger.warning("⚠️  Emails will fail to send. Please configure your .env file.")
        logger.warning("⚠️  Set DRY_RUN=true to test without sending emails.")

    # Create SMTP notifier with configuration
    try:
        smtp = SMTPNotifier(**smtp_config)
        logger.info("✅ SMTPNotifier created successfully")
    except Exception as e:
        logger.error(f"❌ Failed to create SMTPNotifier: {e}")
        logger.error("Check your SMTP configuration in .env file")
        sys.exit(1)

    manager = NotificationManager(rate_limit_seconds=1.0)
    manager.register(smtp)

    processor = NotificationProcessor(manager=manager)

    consumer = Consumer(
        redis_url=REDIS_URL,
        stream_name=MQ_STREAM,
        consumer_group="notification_service_group",
        consumer_name="notification_worker",
    )

    try:
        logger.info("Notification service ready — waiting for events...")
        consumer.consume(handler=processor.process_event, block=5000, count=10)

    except KeyboardInterrupt:
        logger.info("Shutting down notification service (keyboard interrupt)")
        stats = {
            "events_processed": processor.events_processed,
            "events_failed": processor.events_failed,
        }
        logger.info(f"Final stats: {stats}")

    except Exception as e:
        logger.error(f"Fatal error in notification service: {e}", exc_info=True)
        sys.exit(1)

    finally:
        consumer.close()
        logger.info("Notification service stopped")


if __name__ == "__main__":
    main()